import type { SegmentTypeSchema, SegmentType, SegmentProps } from './types';

/** Schema definitions for all 15 segment types */
export const SEGMENT_TYPE_SCHEMAS: SegmentTypeSchema[] = [
  {
    id: 'text_card',
    name: '文字卡片',
    icon: 'type',
    defaults: {
      title: '标题文字',
      subtitle: '',
      titleFontSize: 80,
      subtitleFontSize: 48,
      textColor: '#1d1d1f',
      bgColor: '#ffffff',
      bgGradient: true,
      bgGradientColors: ['#1a1a2e', '#16213e'],
      textAlign: 'center',
      animation: 'fadeIn',
      emphasis: '',
      emphasisColor: '#0071e3',
    },
    props: [
      { key: 'title', label: '主标题', type: 'string', required: true },
      { key: 'subtitle', label: '副标题', type: 'string' },
      { key: 'titleFontSize', label: '主标题字号', type: 'number', default: 80, min: 20, max: 140, step: 2 },
      { key: 'subtitleFontSize', label: '副标题字号', type: 'number', default: 48, min: 16, max: 90, step: 2 },
      { key: 'textColor', label: '文字颜色', type: 'color', default: '#1d1d1f' },
      { key: 'bgColor', label: '背景颜色', type: 'color', default: '#ffffff' },
      { key: 'bgGradient', label: '渐变背景', type: 'boolean', default: true },
      { key: 'bgGradientColors', label: '渐变色组', type: 'colorArray' },
      { key: 'textAlign', label: '对齐方式', type: 'enum', options: ['left', 'center', 'right'], default: 'center' },
      { key: 'animation', label: '动画方式', type: 'enum', options: ['fadeIn', 'slideUp', 'scaleIn', 'typewriter'], default: 'fadeIn' },
      { key: 'emphasis', label: '高亮文字', type: 'string' },
      { key: 'emphasisColor', label: '高亮颜色', type: 'color', default: '#0071e3' },
    ],
  },
  {
    id: 'bar_chart',
    name: '柱状图',
    icon: 'bar-chart-3',
    defaults: {
      title: '数据对比',
      data: [
        { label: 'A', value: 30, color: '#0071e3' },
        { label: 'B', value: 60, color: '#5ac8fa' },
        { label: 'C', value: 90, color: '#ff6b35' },
      ],
      maxValue: 0,
      unit: '',
      showValues: true,
      animation: 'grow',
      barWidth: 0.65,
      barGap: 30,
    },
    props: [
      { key: 'title', label: '图表标题', type: 'string', required: true },
      { key: 'data', label: '数据项', type: 'data' },
      { key: 'maxValue', label: 'Y轴最大值', type: 'number', default: 0, min: 0, step: 1 },
      { key: 'unit', label: '数值单位', type: 'string' },
      { key: 'showValues', label: '显示数值', type: 'boolean', default: true },
      { key: 'animation', label: '动画方式', type: 'enum', options: ['grow', 'slideIn'], default: 'grow' },
      { key: 'barWidth', label: '柱子宽度', type: 'number', default: 0.65, min: 0.2, max: 1, step: 0.05 },
      { key: 'barGap', label: '柱子间距', type: 'number', default: 30, min: 10, max: 100, step: 5 },
    ],
  },
  {
    id: 'pie_chart',
    name: '饼图',
    icon: 'pie-chart',
    defaults: {
      title: '占比分析',
      data: [
        { label: 'A', value: 40, color: '#0071e3' },
        { label: 'B', value: 35, color: '#5ac8fa' },
        { label: 'C', value: 25, color: '#ff6b35' },
      ],
      showLabels: true,
      showPercent: true,
      showLegend: true,
      animation: 'expand',
      donutMode: true,
      centerText: '',
    },
    props: [
      { key: 'title', label: '图表标题', type: 'string', required: true },
      { key: 'data', label: '数据项', type: 'data' },
      { key: 'showLabels', label: '显示标签', type: 'boolean', default: true },
      { key: 'showPercent', label: '显示百分比', type: 'boolean', default: true },
      { key: 'showLegend', label: '显示图例', type: 'boolean', default: true },
      { key: 'animation', label: '动画方式', type: 'enum', options: ['expand', 'fadeIn'], default: 'expand' },
      { key: 'donutMode', label: '环形模式', type: 'boolean', default: true },
      { key: 'centerText', label: '中心文字', type: 'string' },
    ],
  },
  {
    id: 'line_chart',
    name: '折线图',
    icon: 'trending-up',
    defaults: {
      title: '趋势分析',
      series: [
        { name: '系列1', data: [10, 30, 25, 50, 45, 70], color: '#0071e3' },
        { name: '系列2', data: [5, 20, 35, 30, 55, 60], color: '#ff6b35' },
      ],
      xLabels: ['1月', '2月', '3月', '4月', '5月', '6月'],
      yMax: 0,
      showDots: true,
      showGrid: true,
      animation: 'draw',
      fillArea: true,
    },
    props: [
      { key: 'title', label: '图表标题', type: 'string', required: true },
      { key: 'series', label: '数据系列', type: 'data' },
      { key: 'xLabels', label: 'X轴标签', type: 'data' },
      { key: 'yMax', label: 'Y轴最大值', type: 'number', default: 0, min: 0, step: 1 },
      { key: 'showDots', label: '显示数据点', type: 'boolean', default: true },
      { key: 'showGrid', label: '显示网格', type: 'boolean', default: true },
      { key: 'animation', label: '动画方式', type: 'enum', options: ['draw', 'fadeIn'], default: 'draw' },
      { key: 'fillArea', label: '填充区域', type: 'boolean', default: true },
    ],
  },
  {
    id: 'keyword_highlight',
    name: '关键词高亮',
    icon: 'highlighter',
    defaults: {
      text: '关键词',
      fontSize: 130,
      textColor: '#ffffff',
      glowColor: '#0071e3',
      glowRadius: 50,
      bgColor: '#1a1a2e',
      animation: 'pulse',
      pulseScale: 1.15,
    },
    props: [
      { key: 'text', label: '关键词文字', type: 'string', required: true },
      { key: 'fontSize', label: '字号', type: 'number', default: 130, min: 30, max: 180, step: 2 },
      { key: 'textColor', label: '文字颜色', type: 'color', default: '#ffffff' },
      { key: 'glowColor', label: '发光颜色', type: 'color', default: '#0071e3' },
      { key: 'glowRadius', label: '发光半径', type: 'number', default: 50, min: 0, max: 100, step: 2 },
      { key: 'bgColor', label: '背景颜色', type: 'color', default: '#1a1a2e' },
      { key: 'animation', label: '动画方式', type: 'enum', options: ['pulse', 'glow', 'scaleIn'], default: 'pulse' },
      { key: 'pulseScale', label: '脉冲幅度', type: 'number', default: 1.15, min: 1, max: 1.5, step: 0.05 },
    ],
  },
  {
    id: 'quote_card',
    name: '引用金句',
    icon: 'quote',
    defaults: {
      quote: '这里是一段引用金句文字',
      author: '— 作者',
      quoteFontSize: 58,
      authorFontSize: 34,
      quoteColor: '#1d1d1f',
      authorColor: '#6e6e73',
      bgColor: '#ffffff',
      showQuoteMark: true,
      quoteMarkStyle: 'double',
      animation: 'fadeIn',
    },
    props: [
      { key: 'quote', label: '引用文字', type: 'string', required: true },
      { key: 'author', label: '作者/来源', type: 'string' },
      { key: 'quoteFontSize', label: '引用字号', type: 'number', default: 58, min: 24, max: 90, step: 2 },
      { key: 'authorFontSize', label: '作者字号', type: 'number', default: 34, min: 16, max: 60, step: 2 },
      { key: 'quoteColor', label: '引用颜色', type: 'color', default: '#1d1d1f' },
      { key: 'authorColor', label: '作者颜色', type: 'color', default: '#6e6e73' },
      { key: 'bgColor', label: '背景颜色', type: 'color', default: '#ffffff' },
      { key: 'showQuoteMark', label: '显示引号', type: 'boolean', default: true },
      { key: 'quoteMarkStyle', label: '引号样式', type: 'enum', options: ['double', 'single', 'block'], default: 'double' },
      { key: 'animation', label: '动画方式', type: 'enum', options: ['fadeIn', 'slideUp', 'scaleIn'], default: 'fadeIn' },
    ],
  },
  {
    id: 'image_show',
    name: '图片展示',
    icon: 'image',
    defaults: {
      imageUrl: 'https://picsum.photos/1080/1920',
      fit: 'cover',
      filter: 'none',
      overlayText: '',
      overlayPosition: 'center',
      animation: 'kenBurns',
      kenBurnsScale: 1.3,
      kenBurnsDirection: 'zoomIn',
      roundedCorners: 0,
    },
    props: [
      { key: 'imageUrl', label: '图片URL', type: 'string', required: true },
      { key: 'fit', label: '填充方式', type: 'enum', options: ['cover', 'contain', 'fill'], default: 'cover' },
      { key: 'filter', label: '滤镜', type: 'enum', options: ['none', 'grayscale', 'sepia', 'blur', 'darken'], default: 'none' },
      { key: 'overlayText', label: '叠加文字', type: 'string' },
      { key: 'overlayPosition', label: '文字位置', type: 'enum', options: ['top', 'center', 'bottom'], default: 'center' },
      { key: 'animation', label: '动画方式', type: 'enum', options: ['kenBurns', 'fadeIn', 'slideIn'], default: 'kenBurns' },
      { key: 'kenBurnsScale', label: '缩放幅度', type: 'number', default: 1.3, min: 1, max: 2, step: 0.05 },
      { key: 'kenBurnsDirection', label: '缩放方向', type: 'enum', options: ['zoomIn', 'zoomOut', 'panLeft', 'panRight', 'panUp', 'panDown'], default: 'zoomIn' },
      { key: 'roundedCorners', label: '圆角', type: 'number', default: 0, min: 0, max: 100, step: 2 },
    ],
  },
  {
    id: 'process_flow',
    name: '流程步骤',
    icon: 'git-branch',
    defaults: {
      title: '操作流程',
      steps: [
        { title: '步骤一', description: '第一步说明' },
        { title: '步骤二', description: '第二步说明' },
        { title: '步骤三', description: '第三步说明' },
      ],
      layout: 'vertical',
      showConnector: true,
      connectorStyle: 'arrow',
      animation: 'sequential',
      stepDelay: 0.4,
      iconType: 'number',
    },
    props: [
      { key: 'title', label: '流程标题', type: 'string', required: true },
      { key: 'steps', label: '步骤列表', type: 'data' },
      { key: 'layout', label: '布局方向', type: 'enum', options: ['vertical', 'horizontal'], default: 'vertical' },
      { key: 'showConnector', label: '显示连接线', type: 'boolean', default: true },
      { key: 'connectorStyle', label: '连接线样式', type: 'enum', options: ['line', 'arrow', 'dashed'], default: 'arrow' },
      { key: 'animation', label: '动画方式', type: 'enum', options: ['sequential', 'fadeInAll'], default: 'sequential' },
      { key: 'stepDelay', label: '逐步间隔(秒)', type: 'number', default: 0.4, min: 0.1, max: 2, step: 0.1 },
      { key: 'iconType', label: '图标类型', type: 'enum', options: ['number', 'dot', 'check'], default: 'number' },
    ],
  },
  {
    id: 'persona_card',
    name: '人物介绍',
    icon: 'user',
    defaults: {
      name: '人物姓名',
      title: '头衔/职位',
      description: '人物描述文字',
      avatarUrl: '',
      avatarShape: 'circle',
      bgColor: '#ffffff',
      animation: 'slideLeft',
      showBorder: true,
      borderColor: '#0071e3',
    },
    props: [
      { key: 'name', label: '姓名', type: 'string', required: true },
      { key: 'title', label: '头衔', type: 'string' },
      { key: 'description', label: '描述', type: 'string' },
      { key: 'avatarUrl', label: '头像URL', type: 'string' },
      { key: 'avatarShape', label: '头像形状', type: 'enum', options: ['circle', 'square', 'rounded'], default: 'circle' },
      { key: 'bgColor', label: '背景颜色', type: 'color', default: '#ffffff' },
      { key: 'animation', label: '动画方式', type: 'enum', options: ['slideLeft', 'slideRight', 'fadeIn', 'scaleIn'], default: 'slideLeft' },
      { key: 'showBorder', label: '头像边框', type: 'boolean', default: true },
      { key: 'borderColor', label: '边框颜色', type: 'color', default: '#0071e3' },
    ],
  },
  {
    id: 'compare_card',
    name: '对比卡片',
    icon: 'columns',
    defaults: {
      title: '对比分析',
      leftLabel: 'Before',
      rightLabel: 'After',
      leftContent: '之前的状态',
      rightContent: '之后的状态',
      leftColor: '#6e6e73',
      rightColor: '#0071e3',
      layout: 'sideBySide',
      animation: 'expand',
      dividerStyle: 'VS',
    },
    props: [
      { key: 'title', label: '对比标题', type: 'string', required: true },
      { key: 'leftLabel', label: '左侧标签', type: 'string' },
      { key: 'rightLabel', label: '右侧标签', type: 'string' },
      { key: 'leftContent', label: '左侧内容', type: 'string' },
      { key: 'rightContent', label: '右侧内容', type: 'string' },
      { key: 'leftColor', label: '左侧颜色', type: 'color', default: '#6e6e73' },
      { key: 'rightColor', label: '右侧颜色', type: 'color', default: '#0071e3' },
      { key: 'layout', label: '布局方式', type: 'enum', options: ['sideBySide', 'topBottom'], default: 'sideBySide' },
      { key: 'animation', label: '动画方式', type: 'enum', options: ['slideLeft', 'expand', 'fadeIn'], default: 'expand' },
      { key: 'dividerStyle', label: '分割样式', type: 'enum', options: ['line', 'VS', 'none'], default: 'VS' },
    ],
  },
  {
    id: 'number_animation',
    name: '数字动画',
    icon: 'hash',
    defaults: {
      startValue: 0,
      endValue: 100,
      prefix: '',
      suffix: '%',
      decimals: 0,
      fontSize: 160,
      textColor: '#0071e3',
      bgColor: '#ffffff',
      label: '增长指标',
      easing: 'easeOut',
    },
    props: [
      { key: 'startValue', label: '起始数字', type: 'number', default: 0, step: 1 },
      { key: 'endValue', label: '结束数字', type: 'number', default: 100, step: 1 },
      { key: 'prefix', label: '前缀', type: 'string' },
      { key: 'suffix', label: '后缀', type: 'string' },
      { key: 'decimals', label: '小数位数', type: 'number', default: 0, min: 0, max: 4, step: 1 },
      { key: 'fontSize', label: '字号', type: 'number', default: 160, min: 40, max: 220, step: 2 },
      { key: 'textColor', label: '数字颜色', type: 'color', default: '#0071e3' },
      { key: 'bgColor', label: '背景颜色', type: 'color', default: '#ffffff' },
      { key: 'label', label: '说明文字', type: 'string' },
      { key: 'easing', label: '缓动函数', type: 'enum', options: ['linear', 'easeOut', 'easeInOut', 'bounce'], default: 'easeOut' },
    ],
  },
  {
    id: 'tag_cloud',
    name: '标签云',
    icon: 'tags',
    defaults: {
      tags: [
        { text: 'AI', color: '#0071e3' },
        { text: 'Machine Learning', color: '#5ac8fa' },
        { text: 'Deep Learning', color: '#ff6b35' },
        { text: 'NLP', color: '#34c759' },
        { text: 'Computer Vision', color: '#ff9500' },
      ],
      bgColor: '#ffffff',
      layout: 'grid',
      animation: 'fadeInSequential',
      staggerDelay: 0.12,
      minFontSize: 34,
      maxFontSize: 68,
    },
    props: [
      { key: 'tags', label: '标签列表', type: 'data' },
      { key: 'bgColor', label: '背景颜色', type: 'color', default: '#ffffff' },
      { key: 'layout', label: '布局方式', type: 'enum', options: ['random', 'grid', 'spiral'], default: 'grid' },
      { key: 'animation', label: '动画方式', type: 'enum', options: ['fadeInSequential', 'fadeInAll', 'floatIn'], default: 'fadeInSequential' },
      { key: 'staggerDelay', label: '间隔(秒)', type: 'number', default: 0.12, min: 0.05, max: 1, step: 0.05 },
      { key: 'minFontSize', label: '最小字号', type: 'number', default: 34, min: 16, max: 48, step: 2 },
      { key: 'maxFontSize', label: '最大字号', type: 'number', default: 68, min: 36, max: 120, step: 2 },
    ],
  },
  {
    id: 'progress_timeline',
    name: '进度时间线',
    icon: 'milestone',
    defaults: {
      title: '项目进度',
      nodes: [
        { label: '启动', color: '#34c759' },
        { label: '开发', color: '#0071e3' },
        { label: '测试', color: '#ff9500' },
        { label: '上线', color: '#6e6e73' },
      ],
      layout: 'horizontal',
      lineStyle: 'gradient',
      nodeShape: 'circle',
      animation: 'draw',
      showProgress: true,
    },
    props: [
      { key: 'title', label: '标题', type: 'string', required: true },
      { key: 'nodes', label: '节点列表', type: 'data' },
      { key: 'layout', label: '布局方向', type: 'enum', options: ['horizontal', 'vertical'], default: 'horizontal' },
      { key: 'lineStyle', label: '线条样式', type: 'enum', options: ['solid', 'dashed', 'gradient'], default: 'gradient' },
      { key: 'nodeShape', label: '节点形状', type: 'enum', options: ['circle', 'diamond', 'square'], default: 'circle' },
      { key: 'animation', label: '动画方式', type: 'enum', options: ['draw', 'fadeIn'], default: 'draw' },
      { key: 'showProgress', label: '显示进度', type: 'boolean', default: true },
    ],
  },
  {
    id: 'end_card',
    name: '结尾卡片',
    icon: 'flag',
    defaults: {
      brandName: 'VisualForge',
      slogan: '代码驱动的视觉动画渲染',
      ctaText: '立即体验',
      ctaUrl: '',
      bgColor: '#1a1a2e',
      animation: 'fadeIn',
      fadeOut: true,
    },
    props: [
      { key: 'brandName', label: '品牌名称', type: 'string', required: true },
      { key: 'slogan', label: '标语', type: 'string' },
      { key: 'ctaText', label: '行动号召', type: 'string' },
      { key: 'ctaUrl', label: '链接地址', type: 'string' },
      { key: 'bgColor', label: '背景颜色', type: 'color', default: '#1a1a2e' },
      { key: 'animation', label: '动画方式', type: 'enum', options: ['fadeIn', 'scaleIn', 'slideUp'], default: 'fadeIn' },
      { key: 'fadeOut', label: '结尾淡出', type: 'boolean', default: true },
    ],
  },
  {
    id: 'background',
    name: '背景效果',
    icon: 'layers',
    defaults: {
      type: 'gradient',
      color: '#0d1117',
      gradientColors: ['#1a1a2e', '#16213e'],
      gradientDirection: 'diagonal',
      particleCount: 50,
      particleColor: '#0071e3',
      particleSpeed: 1,
      gridColor: '#30363d',
      gridSpacing: 60,
      animated: true,
    },
    props: [
      { key: 'type', label: '背景类型', type: 'enum', options: ['solid', 'gradient', 'particles', 'grid', 'dots'], default: 'gradient' },
      { key: 'color', label: '纯色背景', type: 'color', default: '#0d1117' },
      { key: 'gradientColors', label: '渐变色组', type: 'colorArray' },
      { key: 'gradientDirection', label: '渐变方向', type: 'enum', options: ['vertical', 'horizontal', 'radial', 'diagonal'], default: 'diagonal' },
      { key: 'particleCount', label: '粒子数量', type: 'number', default: 50, min: 10, max: 200, step: 5 },
      { key: 'particleColor', label: '粒子颜色', type: 'color', default: '#0071e3' },
      { key: 'particleSpeed', label: '粒子速度', type: 'number', default: 1, min: 0.1, max: 5, step: 0.1 },
      { key: 'gridColor', label: '网格颜色', type: 'color', default: '#30363d' },
      { key: 'gridSpacing', label: '网格间距', type: 'number', default: 60, min: 20, max: 200, step: 10 },
      { key: 'animated', label: '动画', type: 'boolean', default: true },
    ],
  },
];

/** Get schema by segment type ID */
export function getSegmentSchema(type: SegmentType): SegmentTypeSchema | undefined {
  return SEGMENT_TYPE_SCHEMAS.find((s) => s.id === type);
}

/** Get default props for a segment type */
export function getDefaultProps(type: SegmentType): SegmentProps {
  const schema = getSegmentSchema(type);
  if (!schema) {
    throw new Error(`Unknown segment type: ${type}`);
  }
  return { ...schema.defaults } as unknown as SegmentProps;
}

/** Segment type display names for the library sidebar */
export const SEGMENT_LIBRARY: { type: SegmentType; name: string; icon: string }[] = [
  { type: 'text_card', name: '文字卡片', icon: 'type' },
  { type: 'bar_chart', name: '柱状图', icon: 'bar-chart-3' },
  { type: 'pie_chart', name: '饼图', icon: 'pie-chart' },
  { type: 'line_chart', name: '折线图', icon: 'trending-up' },
  { type: 'keyword_highlight', name: '关键词高亮', icon: 'highlighter' },
  { type: 'quote_card', name: '引用金句', icon: 'quote' },
  { type: 'image_show', name: '图片展示', icon: 'image' },
  { type: 'process_flow', name: '流程步骤', icon: 'git-branch' },
  { type: 'persona_card', name: '人物介绍', icon: 'user' },
  { type: 'compare_card', name: '对比卡片', icon: 'columns' },
  { type: 'number_animation', name: '数字动画', icon: 'hash' },
  { type: 'tag_cloud', name: '标签云', icon: 'tags' },
  { type: 'progress_timeline', name: '进度时间线', icon: 'milestone' },
  { type: 'end_card', name: '结尾卡片', icon: 'flag' },
  { type: 'background', name: '背景效果', icon: 'layers' },
];
