import type { Theme } from './types';

/** Built-in themes */
export const THEMES: Theme[] = [
  {
    id: 'tech_blue',
    name: 'Tech Blue',
    tokens: {
      primaryColor: '#0071e3',
      secondaryColor: '#5ac8fa',
      accentColor: '#ff6b35',
      bgColor: '#f5f5f7',
      bgDarkColor: '#1a1a2e',
      textColor: '#1d1d1f',
      textSecondaryColor: '#6e6e73',
      cardBgColor: '#ffffff',
      cardBgDarkColor: '#16213e',
      chartColors: ['#0071e3', '#5ac8fa', '#ff6b35', '#34c759', '#ff9500'],
      fontFamily: '"WQY Micro Hei", "PingFang SC", "Microsoft YaHei", sans-serif',
      titleFontSize: 64,
      subtitleFontSize: 36,
      bodyFontSize: 28,
      borderRadius: 16,
      shadow: '0 8px 32px rgba(0,0,0,0.12)',
    },
  },
  {
    id: 'dark_mode',
    name: 'Dark Mode',
    tokens: {
      primaryColor: '#00d4aa',
      secondaryColor: '#00a8ff',
      accentColor: '#ff6b35',
      bgColor: '#0d1117',
      bgDarkColor: '#161b22',
      textColor: '#e6edf3',
      textSecondaryColor: '#7d8590',
      cardBgColor: '#161b22',
      cardBgDarkColor: '#21262d',
      chartColors: ['#00d4aa', '#00a8ff', '#ff6b35', '#facc15', '#a78bfa'],
      fontFamily: '"WQY Micro Hei", "PingFang SC", "Microsoft YaHei", sans-serif',
      titleFontSize: 64,
      subtitleFontSize: 36,
      bodyFontSize: 28,
      borderRadius: 16,
      shadow: '0 8px 32px rgba(0,0,0,0.4)',
    },
  },
  {
    id: 'business_gray',
    name: 'Business Gray',
    tokens: {
      primaryColor: '#333333',
      secondaryColor: '#666666',
      accentColor: '#007acc',
      bgColor: '#ffffff',
      bgDarkColor: '#1a1a1a',
      textColor: '#1a1a1a',
      textSecondaryColor: '#666666',
      cardBgColor: '#f8f9fa',
      cardBgDarkColor: '#2d2d2d',
      chartColors: ['#333333', '#666666', '#007acc', '#28a745', '#ffc107'],
      fontFamily: '"WQY Micro Hei", "PingFang SC", "Microsoft YaHei", sans-serif',
      titleFontSize: 64,
      subtitleFontSize: 36,
      bodyFontSize: 28,
      borderRadius: 8,
      shadow: '0 4px 20px rgba(0,0,0,0.08)',
    },
  },
  {
    id: 'vibrant_orange',
    name: 'Vibrant Orange',
    tokens: {
      primaryColor: '#ff6b35',
      secondaryColor: '#ffa500',
      accentColor: '#004e89',
      bgColor: '#fff8f0',
      bgDarkColor: '#2d1b0e',
      textColor: '#2d1b0e',
      textSecondaryColor: '#8b5e3c',
      cardBgColor: '#ffffff',
      cardBgDarkColor: '#3d2817',
      chartColors: ['#ff6b35', '#ffa500', '#004e89', '#28a745', '#e63946'],
      fontFamily: '"WQY Micro Hei", "PingFang SC", "Microsoft YaHei", sans-serif',
      titleFontSize: 64,
      subtitleFontSize: 36,
      bodyFontSize: 28,
      borderRadius: 20,
      shadow: '0 8px 32px rgba(255,107,53,0.15)',
    },
  },
  {
    id: 'warm_earth',
    name: 'Warm Earth',
    tokens: {
      primaryColor: '#8b6914',
      secondaryColor: '#a0522d',
      accentColor: '#cd853f',
      bgColor: '#faf3e0',
      bgDarkColor: '#3e2723',
      textColor: '#3e2723',
      textSecondaryColor: '#6d4c41',
      cardBgColor: '#fff8e7',
      cardBgDarkColor: '#4e342e',
      chartColors: ['#8b6914', '#a0522d', '#cd853f', '#6d4c41', '#d4a373'],
      fontFamily: '"WQY Micro Hei", "PingFang SC", "Microsoft YaHei", serif',
      titleFontSize: 64,
      subtitleFontSize: 36,
      bodyFontSize: 28,
      borderRadius: 12,
      shadow: '0 6px 24px rgba(62,39,35,0.12)',
    },
  },
  {
    id: 'minimal_white',
    name: 'Minimal White',
    tokens: {
      primaryColor: '#000000',
      secondaryColor: '#333333',
      accentColor: '#ff3b30',
      bgColor: '#ffffff',
      bgDarkColor: '#f5f5f5',
      textColor: '#000000',
      textSecondaryColor: '#999999',
      cardBgColor: '#ffffff',
      cardBgDarkColor: '#f0f0f0',
      chartColors: ['#000000', '#666666', '#ff3b30', '#007aff', '#34c759'],
      fontFamily: '"WQY Micro Hei", "PingFang SC", "Microsoft YaHei", sans-serif',
      titleFontSize: 64,
      subtitleFontSize: 36,
      bodyFontSize: 28,
      borderRadius: 4,
      shadow: '0 2px 12px rgba(0,0,0,0.06)',
    },
  },
  {
    id: 'neon_night',
    name: 'Neon Night',
    tokens: {
      primaryColor: '#ff00ff',
      secondaryColor: '#00ffff',
      accentColor: '#ffff00',
      bgColor: '#0a0a0a',
      bgDarkColor: '#121212',
      textColor: '#ff00ff',
      textSecondaryColor: '#888888',
      cardBgColor: '#1a1a2e',
      cardBgDarkColor: '#16213e',
      chartColors: ['#ff00ff', '#00ffff', '#ffff00', '#ff0066', '#00ff88'],
      fontFamily: '"WQY Micro Hei", "PingFang SC", "Microsoft YaHei", sans-serif',
      titleFontSize: 64,
      subtitleFontSize: 36,
      bodyFontSize: 28,
      borderRadius: 24,
      shadow: '0 0 30px rgba(255,0,255,0.3)',
    },
  },
];

/** Get theme by ID, fallback to tech_blue */
export function getTheme(themeId: string): Theme {
  return THEMES.find((t) => t.id === themeId) ?? THEMES[0];
}
